using MongoDB.Bson;

namespace MongoDb.Driver.Shared.Utils;

public static class IdGenerator
{
    /// <summary>
    /// Generates a new Id
    /// </summary>
    /// <remarks>
    /// The Id is a <see cref="ObjectId"/> generated by MongoDb library
    /// </remarks>
    /// <returns>New Id for an entity</returns>
    public static string GenerateId()
    {
        ObjectId newId = ObjectId.GenerateNewId();
        return newId.ToString();
    }
}
